### ISSUE TITLE
How to deploy ovn-kubernetes using Mellanox Blue-Field3

### ISSUE THREAD

**Issue by starflyyy3119** [ovn-kubernetes/ovn-kubernetes#4673]
### What would you like to know?

We are using Mellanox Blue-Field3 DPU with ovn-kubernetes. However, the deployment guide in the user guide is banned. https://docs.google.com/document/d/1hRke0cOCY84Ef8OU283iPg_PHiJ6O17aUkb9Vv-fWPQ/edit?usp=sharing I'd appreciate if you can add my account to your doc list. It helps a lot.Moreover, would it be ok for me to see this DPU design doc: https://docs.google.com/document/d/11IoMKiohK7hIyIE36FJmwJv46DEBx52a4fqvrpCBBcg/edit#heading=h.hzgdz5n9jmiv

**Comment by tssurya** [comment]
@girishmg could we please have someone from Nvidia port these docs to upstream
ovn-kubernetes.io ?

Thanks for opening the issue @starflyyy3119 ! If you don't mind me asking which org are you from? What's the email we need to share the doc with? Perhaps better to also add you to our slack channel (for which I'd need your email)

**Comment by starflyyy3119** [comment]
starfly3119@gmail.com

**Comment by tssurya** [comment]
thanks for your email; have sent an invite to our slack channel
