### ISSUE TITLE
ovnkube-node DaemonSet: Tolerate Everything?

### ISSUE THREAD

**Issue by flavio-fernandes** [ovn-kubernetes/ovn-kubernetes#4891]
### What would you like to know?

# ovnkube-node DaemonSet: Tolerate Everything?

Currently, the `daemonset.apps/ovnkube-node` uses a "tolerate everything" approach, and I wonder if there is a valid reason for it.  
It seems that OpenShift also follows this pattern: [OpenShift OVN-Kubernetes YAML](https://github.com/openshift/cluster-network-operator/blob/7736bfe37f1276f771fcef03077f6d840eb6b862/bindata/network/ovn-kubernetes/self-hosted/ovnkube-node.yaml#L831-L832).

For DaemonSets specifically, Kubernetes automatically adds the following tolerations to all Pods:

- `node.kubernetes.io/not-ready`  
- `node.kubernetes.io/unreachable`  
- `node.kubernetes.io/disk-pressure`  
- `node.kubernetes.io/memory-pressure`  
- `node.kubernetes.io/pid-pressure`  
- `node.kubernetes.io/unschedulable`  
- `node.kubernetes.io/network-unavailable` (**host-networked Pods only**)

This behavior is documented here: [Kubernetes DaemonSet Taints and Tolerations](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations).

Isn't that sufficient? Can you think of a specific taint that would pose a problem for Pods created by any of the `ovn-kubernetes` DaemonSets?  
If not, the "tolerate everything" approach for DaemonSets might not be necessary. What do you think?

**Comment by kyrtapz** [comment]
Hey @flavio-fernandes!
I think we need to tolerate all taints as otherwise there would be no overlay networking available on excluded nodes.
Users can create custom taints that we won't be able to predict.

**Comment by flavio-fernandes** [comment]
> Hey @flavio-fernandes! I think we need to tolerate all taints as otherwise there would be no overlay networking available on excluded nodes. Users can create custom taints that we won't be able to predict.

I see, @kyrtapz. In clusters where users can create unpredictable taints, using `tolerate anything` makes a lot of sense for ovn-k8s to ensure the CNI remains functional.
